#!/bin/bash
read -p "This will overwrite your current configuration files. Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

rm -rf ~/.config/fish
ln -sf $(pwd)/fish ~/.config/fish
rm -rf ~/.config/i3
ln -sf $(pwd)/i3 ~/.config/i3
ln -sf $(pwd)/inputrc ~/.inputrc
ln -sf $(pwd)/vimrc ~/.vimrc
ln -sf $(pwd)/tmux.conf ~/.tmux.conf
