require('which-key').setup()

require('which-key').register {
    ['<leader>'] = {
        b = { '<cmd>BufferLinePick<cr>', 'Jump to buffer' },
        c = { '<cmd>bdelete<cr>', 'Close buffer' },
        C = { '<cmd>edit $MYVIMRC<cr>', 'Edit config' },
        d = {
            name = '+Debug',
            b = { '<plug>VimspectorToggleBreakpoint', 'Breakpoint' },
            c = { '<plug>VimspectorContinue', 'Continue' },
            g = { '<plug>VimspectorContinue', 'Go' },
            i = { '<plug>VimspectorStepInto', 'Step into' },
            o = { '<plug>VimspectorStepOver', 'Step over' },
            p = { '<plug>VimspectorPause', 'Pause' },
            s = { '<plug>VimspectorStop', 'Stop' },
            q = { '<cmd>VimspectorReset<cr>', 'Quit' },
            r = { '<plug>VimspectorRestart', 'Restart' },
        },
        e = { '<cmd>NvimTreeToggle<cr>', 'Explorer' },
        f = { '<cmd>Telescope find_files<cr>', 'Find file' },
        h = { '<cmd>HopChar1<cr>', 'Hop' },
        l = {
            name = '+Lsp',
            a = { '<plug>(coc-codeaction-selected)', 'Code action (selected)' },
            A = { '<plug>(coc-codeaction)', 'Code action (buffer)' },
            c = { '<cmd>CocConfig<cr>', 'Configure' },
            d = { '<cmd>CocDiagnostics<cr>', 'Diagnostics' },
            f = { '<cmd>call CocAction("format")<cr>', 'Format' },
            l = { '<plug>(coc-codelens-action)', 'CodeLens action' },
            q = { '<plug>(coc-fix-current)', 'Quick fix' },
            r = { '<plug>(coc-rename)', 'Rename' },
        },
        o = { '<cmd>SymbolsOutline<cr>', 'Outline' },
        p = { '"+p', "Put clipboard" },
        P = {
            name = '+Packer',
            c = { '<cmd>PackerCompile<cr>', 'Compile' },
            C = { '<cmd>PackerClean<cr>', 'Clean' },
            i = { '<cmd>PackerInstall<cr>', 'Install' },
            s = { '<cmd>PackerSync<cr>', 'Sync' },
            S = { '<cmd>PackerStatus<cr>', 'Status' },
            u = { '<cmd>PackerUpdate<cr>', 'Update' },
        },
        q = { '<cmd>quit<cr>', 'Quit' },
        s = {
            name = '+Search',
            b = { '<cmd>Telescope buffers<cr>', 'Buffers' },
            c = { '<cmd>lua require("telescope.builtin.internal").colorscheme({ enable_preview = true })<cr>', 'Colorscheme' },
            f = { '<cmd>Telescope find_files<cr>', 'Files' },
            k = { '<cmd>Telescope keymaps<cr>', 'Key mappings' },
            p = { '<cmd>Telescope projects<cr>', 'Projects' },
            r = { '<cmd>Telescope oldfiles<cr>', 'Recent files' },
            t = { '<cmd>Telescope live_grep<cr>', 'Text' },
            w = { '<cmd>Telescope grep_string<cr>', 'Word under cursor' },
        },
        t = {
            name = '+Tasks',
            b = { '<cmd>AsyncTask project-build<cr>', 'Build' },
            e = { '<cmd>AsyncTaskEdit<cr>', 'Edit tasks' },
            l = { '<cmd>AsyncTaskList<cr>', 'List tasks' },
            p = { '<cmd>AsyncTaskProfile debug release<cr>', 'Profile' },
            r = { '<cmd>AsyncTask project-run<cr>', 'Run' },
        },
        T = { '<cmd>Trouble<cr>', 'Trouble' },
        w = { '<cmd>write<cr>', 'Write' },
        y = { '"+y', "Yank clipboard" },
    },
}

require('which-key').register({
    ['<leader>'] = {
        p = { '"+p', "Put clipboard" },
        y = { '"+y', "Yank clipboard" },
    },
},
{ mode = 'v' })
